apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  namespace: web
spec:
  containers:
  - name: helloworld
    image: core.hanium-devops.site/devops/helloworld:19
#    ports:
#      - containerPort: 8080
  imagePullSecrets:
  - name: harbor-repo
