apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  namespace: web
spec:
  containers:
  - name: helloworld
    image: core.hanium-devops.site/devops/helloworld:latest
    args: [/bin/sh, -c, 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
    ports:
      - containerPort: 8080
  imagePullSecrets:
  - name: harbor-repo
