apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: standard
  name: prometheus
  labels:
    app: prometheus
spec:
 accessModes:
  - ReadWriteOnce
 capacity:
   storage: 10Gi
 nfs:
   path: /storage/prometheus
   server: 10.0.1.37
 persistentVolumeReclaimPolicy: Retain
 volumeMode: Filesystem