apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: standard
  name: jenkins
spec:
 accessModes:
  - ReadWriteOnce
 capacity:
   storage: 30Gi
 nfs:
   path: /storage/efk
   server: 10.0.1.37
 persistentVolumeReclaimPolicy: Retain
 volumeMode: Filesystem